# Generated by Django 5.2 on 2025-04-04 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Projeto'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Tarefa'},
        ),
    ]
