# Generated by Django 5.2 on 2025-04-04 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='color',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
