# Generated by Django 5.2 on 2025-04-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_project_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='expires_at',
        ),
        migrations.AddField(
            model_name='task',
            name='expire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='expire_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
